name: GitHub Profile Stats

on:
  schedule:
    - cron: "0 23 * * *"  # ogni giorno alle 23 UTC
  workflow_dispatch:       # permette di far partire manualmente

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:

      # Statistiche generali del profilo
      - name: 'User Stats'
        uses: lowlighter/metrics@latest
        with:
          filename: user.svg
          token: ${{ secrets.GHRS_GITHUB_API_TOKEN }}
          base: header, repositories, stars, commits, community, contributions
          plugin_lines: yes
          plugin_activity: yes
          plugin_activity_include_forks: yes
